"use client";

import { useMemo, useState } from "react";

type Fair = { id:number; title:string; short:string; start:string; end:string; venue:string; area:string; category:"일러스트"|"캐릭터"|"굿즈"; color:string; text:string; icon:string; fee:string; organizer:string; description:string };

const fairs: Fair[] = [
  {id:1,title:"서울 일러스트 페어",short:"서일페 V.20",start:"2026-08-06",end:"2026-08-09",venue:"코엑스 C홀",area:"서울",category:"일러스트",color:"#ff6b4a",text:"#fff",icon:"✹",fee:"12,000원",organizer:"오씨메이커스",description:"개성 넘치는 작가와 브랜드를 한자리에서 만나는 국내 대표 일러스트레이션 페어예요."},
  {id:2,title:"부산 일러스트레이션 페어",short:"부일페 vol.8",start:"2026-08-14",end:"2026-08-16",venue:"벡스코 제2전시장",area:"부산",category:"일러스트",color:"#7564e8",text:"#fff",icon:"☁",fee:"10,000원",organizer:"부일페 사무국",description:"바다의 도시 부산에서 열리는 창작자 중심의 일러스트·디자인 축제입니다."},
  {id:3,title:"캐릭터 라이선싱 페어",short:"캐릭터 라이선싱",start:"2026-08-20",end:"2026-08-23",venue:"코엑스 A·B홀",area:"서울",category:"캐릭터",color:"#f8d55c",text:"#322b20",icon:"●",fee:"15,000원",organizer:"한국콘텐츠진흥원",description:"국내외 인기 캐릭터와 새로운 IP, 라이선싱 비즈니스를 함께 만나는 행사예요."},
  {id:4,title:"대구 크리에이터 마켓",short:"대구 크마",start:"2026-08-22",end:"2026-08-23",venue:"엑스코 서관",area:"대구",category:"굿즈",color:"#34b883",text:"#fff",icon:"✦",fee:"8,000원",organizer:"크리에이터 마켓",description:"지역 창작자의 포스터, 문구, 패브릭과 다양한 독립 굿즈를 소개합니다."},
  {id:5,title:"핸드메이드 코리아",short:"핸드메이드 코리아",start:"2026-08-28",end:"2026-08-30",venue:"수원메쎄",area:"경기",category:"굿즈",color:"#ee7aaa",text:"#fff",icon:"♥",fee:"10,000원",organizer:"메쎄이상",description:"손으로 만든 오브제와 캐릭터 굿즈, 독립 브랜드를 발견하는 라이프스타일 페어입니다."},
];

const days=Array.from({length:42},(_,i)=>i-4); const labels=["일","월","화","수","목","금","토"];

export default function Home(){
  const [selected,setSelected]=useState<Fair|null>(fairs[2]); const [area,setArea]=useState("전체 지역"); const [type,setType]=useState("모든 페어"); const [liked,setLiked]=useState<number[]>([]);
  const visible=useMemo(()=>fairs.filter(f=>(area==="전체 지역"||f.area===area)&&(type==="모든 페어"||f.category===type)),[area,type]);
  const events=(day:number)=>visible.filter(f=>day>=Number(f.start.slice(-2))&&day<=Number(f.end.slice(-2))); const toggle=(id:number)=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">✦</span><span>페어캘린더</span></a><nav><a className="active" href="#calendar">캘린더</a><a href="#list">페어 둘러보기</a></nav><button className="submit-btn" onClick={()=>alert("페어 제보 기능은 곧 열릴 예정이에요!")}>페어 제보하기 <span>↗</span></button></header>
    <section className="hero" id="top"><div><p className="eyebrow">CHARACTER · ILLUSTRATION · GOODS</p><h1>좋아하는 세계를<br/><em>만나러 가는 날.</em></h1><p className="hero-copy">전국의 캐릭터·일러스트 페어 일정을<br/>한눈에 모아보세요.</p></div><div className="hero-art" aria-hidden="true"><div className="spark s1">✦</div><div className="spark s2">✦</div><div className="ticket t1"><b>AUG</b><strong>20</strong><span>CHARACTER<br/>FAIR</span></div><div className="ticket t2"><span>MEET YOUR<br/>FAVORITE WORLD</span><b>♥</b></div><div className="mascot"><div className="ear left"></div><div className="ear right"></div><div className="face"><i></i><i></i><b>ᴗ</b></div></div></div></section>
    <section className="calendar-section" id="calendar"><div className="section-head"><div><span className="mini-label">FAIR CALENDAR</span><h2>2026년 8월</h2></div><div className="filters"><label><span className="sr-only">지역 선택</span><select value={area} onChange={e=>setArea(e.target.value)}><option>전체 지역</option><option>서울</option><option>경기</option><option>부산</option><option>대구</option></select></label><label><span className="sr-only">종류 선택</span><select value={type} onChange={e=>setType(e.target.value)}><option>모든 페어</option><option>일러스트</option><option>캐릭터</option><option>굿즈</option></select></label></div></div>
      <div className="calendar-wrap"><div className="weekdays">{labels.map((l,i)=><div className={i===0?"sun":""} key={l}>{l}</div>)}</div><div className="grid">{days.map((day,i)=>{const valid=day>0&&day<=31;return <div className={`cell ${!valid?"muted":""}`} key={i}><span className={i%7===0?"sun":""}>{valid?day:day<=0?31+day:day-31}</span>{valid&&events(day).map(f=><button key={f.id} className="event" style={{background:f.color,color:f.text}} onClick={()=>setSelected(f)}>{day===Number(f.start.slice(-2))?f.short:""}</button>)}</div>})}</div></div><div className="legend"><span><i className="dot orange"></i>일러스트</span><span><i className="dot yellow"></i>캐릭터</span><span><i className="dot green"></i>굿즈·마켓</span></div>
    </section>
    <section className="list-section" id="list"><div className="section-head"><div><span className="mini-label">UPCOMING FAIRS</span><h2>곧 만나요!</h2></div><p>이번 달 열리는 페어를 날짜순으로 모았어요.</p></div><div className="cards">{visible.slice(0,4).map(f=><article className="card" key={f.id} onClick={()=>setSelected(f)}><div className="poster" style={{background:f.color,color:f.text}}><span>{f.category}</span><strong>{f.icon}</strong><b>{f.short}</b></div><div className="card-body"><div className="card-meta"><span>{f.area}</span><button aria-label="관심 페어 저장" onClick={e=>{e.stopPropagation();toggle(f.id)}}>{liked.includes(f.id)?"♥":"♡"}</button></div><h3>{f.title}</h3><p>{f.start.slice(5).replace("-",".")} — {f.end.slice(5).replace("-",".")}</p><p className="venue">⌖ {f.venue}</p></div></article>)}</div></section>
    {selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="detail" role="dialog" aria-modal="true"><button className="close" onClick={()=>setSelected(null)} aria-label="닫기">×</button><div className="detail-poster" style={{background:selected.color,color:selected.text}}><span>{selected.category.toUpperCase()} FAIR</span><strong>{selected.icon}</strong><b>{selected.short}</b></div><div className="detail-body"><span className="pill">{selected.area} · {selected.category}</span><h2>{selected.title}</h2><p className="desc">{selected.description}</p><dl><div><dt>일정</dt><dd>{selected.start.replaceAll("-",". ")} — {selected.end.slice(5).replace("-",". ")}</dd></div><div><dt>장소</dt><dd>{selected.venue}</dd></div><div><dt>입장료</dt><dd>{selected.fee}</dd></div><div><dt>주최</dt><dd>{selected.organizer}</dd></div></dl><button className="primary" onClick={()=>toggle(selected.id)}>{liked.includes(selected.id)?"♥ 관심 페어에 저장됨":"♡ 관심 페어로 저장"}</button><p className="notice">* 현재 일정은 사이트 시안을 위한 예시 정보입니다.</p></div></aside></div>}
  </main>
}
